encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("new", views.new, name="new"),
    path("create", views.create, name="create"),
    path("randompage", views.randompage, name="randompage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace='encyclopedia'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django import forms
import random

from . import util
import markdown2


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    if title not in util.list_entries():
        return render(request, "encyclopedia/filenotfound.html")
    else:
        return render(request, "encyclopedia/entry.html",{
        'title': title,
        'entry': markdown2.markdown(util.get_entry(title))
        })

def search(request):
    if request.method == "POST":
        result = str(request.POST['q'])
        entries = util.list_entries()
        searchlist = list()
        x = 0
        y = 0
        if result in entries:
            return render(request, "encyclopedia/entry.html",{
            'title': result,
            'entry': markdown2.markdown(util.get_entry(result))
            })
        else:
            for entry in entries:
                if result in entry.lower():
                    searchlist.append(entry)
            return render(request, "encyclopedia/searchresults.html", {
                "entries": searchlist
            })

def edit(request, title):
    if request.method == "GET":
        return render(request, "encyclopedia/editpage.html", {
            "title": title,
            "content": util.get_entry(title)
        })
    else:
        new_content = request.POST.get("edit-content")
        util.save_entry(title, new_content)
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))

#Create a new form
class NewEntry(forms.Form):
    title = forms.CharField(label = "Enter Title")
    text = forms.CharField(label = "Enter Description")


def create(request):
    context = {}
    context['form'] = NewEntry()
    return render(request, "encyclopedia/newpage.html", context)


def new(request):
    entries = util.list_entries()
    if request.method == "POST":
        form = NewEntry(request.POST)
        if form.is_valid():
            text = form.cleaned_data["text"]
            title = form.cleaned_data["title"]
            if title.capitalize() in entries:
                return render(request, "encyclopedia/existingpage.html")
            else:
                util.save_entry(title.capitalize(), text)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title.capitalize()]))

def randompage(request):
    entries = util.list_entries()
    rand_number = random.randint(0, len(entries)-1)
    rand_entry = entries[rand_number]
    return HttpResponseRedirect(reverse("encyclopedia:entry", args=[rand_entry]))

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        {% csrf_token %}
        <h1>Edit Page</h1>
        <textarea rows="1" cols="20" name="edit-content" id="edit-content">{{ content }}</textarea>
        <input type="Submit" value="Save Changes" />
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Encyclopedia
{% endblock %}

{% block body %}
    <div>
       {{ entry | safe}}
       <a href="{% url 'encyclopedia:edit' title %}"> Edit Page</a>
      </div>

{% endblock %}

encyclopedia/templates/encyclopedia/existingpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h3> The page you are trying to create already exists.</h3>
{% endblock %}

encyclopedia/templates/encyclopedia/filenotfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Requested Page Was Not Found</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry.title %}">{{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                      <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a New Page
{% endblock %}

{% block body %}
<form action="{% url 'encyclopedia:new' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
<input type="submit" value="Create">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/searchresults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry.title %}">{{ entry }} </a></li>
            {% empty %}
              <p>
                No results
                </p>
        {% endfor %}
    </ul>

{% endblock %}